# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Thinking Aloud
tagline:             ''
description:         'Web | Unix | DevOps'
url:                 ''
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Cauchy Cai
  url:               https://twitter.com/cauuuuchy
  github:            https://github.com/cauchycai
  email:             cauchy.cai@gmail.com

# Custom vars
version:             1.0.0
